version: "3.9"

services:
  api:
    build:
      context: ./Backend/Domain
      dockerfile: Dockerfile
    ports:
      - 8080:80
    depends_on:
      - mongodb

  bot:
    build:
      context: ./NeoStaffBot
      dockerfile: Dockerfile

  client:
    build:
      context: ./client
      dockerfile: Dockerfile
    ports:
      - 3000:3000

  mongodb:
    image: mongo:latest
    ports:
      - 27017:27017
    environment:
      MONGODB_HOST: mongodb
      MONGODB_PORT: 27017
