version: "3.9"

services:
  api:
    build: 
      context: ./Domain
      dockerfile: Dockerfile
    ports:
      - 8080:80
    depends_on:
      - mongodb

  analytics:
    build: 
      context: ./Analytics
      dockerfile: Dockerfile
    ports:
      - 8081:80
    depends_on:
      - mongodb

  mongodb:
    image: mongo:latest
    ports:
      - 27017:27017
    environment:
      MONGODB_HOST: mongodb
      MONGODB_PORT: 27017